#!/usr/bin/env python3

import element as EL


Infinite = 1000000

FORCE_DUEL = True
#FORCE_DUEL = False
FORCE_HARVEST = False
FORCE_ATTACK_PLAYERS = True
FORCE_STAYED_AT_PORTALS = False

ZOMBIE_CAN_CHANGE_DIRECTION = True

#FLASHING_PERKS = True
FLASHING_PERKS = False


DO_NOT_ATTACK_IMMORTAL = 5 #do not attack if immortal at least X moves
CHECK_BULLET_NEW = True


RATE_DEATH = 100
RATE_RISKY = (RATE_DEATH*3)//4
RATE_VERY_RISKY = (RATE_DEATH*9)//10


DANGER_RATE_DEATH = RATE_DEATH


DANGER_RATE_PLAYER_CAN_FIRE   = (100,90)[FORCE_DUEL]
DANGER_RATE_PLAYER_COULD_FIRE = (80,50)[FORCE_DUEL]


DANGER_AI_SIDEATTACK            = 80
DANGER_AI_SIDEATTACK_SIMULATION = 60

#DANGER_TREE = 0
#DANGER_TREEN_MAP = [DANGER_TREE, 0, 0, 0, 0] #0..4

DANGER_TREE = 0
#DANGER_TREEN_MAP = [DANGER_TREE, 10, 5, 0, 0] #0..4
DANGER_TREEN_MAP = [DANGER_TREE, 30, 20, 0, 0] #0..4

DANGER_ICE  = 5 

# Dangers
DANGER_RATE_ZOMBIE           = RATE_DEATH #death
DANGER_RATE_NEAR_ZOMBIE_FACE = RATE_DEATH #int(RATE_DEATH*0.9)
DANGER_RATE_NEAR_ZOMBIE_BACK = (RATE_DEATH*2)//3

DANGER_RATE_NEAR_PLAYER_BACK = (RATE_DEATH*2)//3 #can fire - high risk
DANGER_RATE_NEAR_PLAYER_FACE = (RATE_DEATH*8)//10 #can fire - high risk
DANGER_RATE_NEAR_PLAYER_DIAG = RATE_DEATH//2
DANGER_RATE_PLAYER           = RATE_DEATH//2 #mrisky to jump - can move and fire


#DANGER_DIST_RADIUS = 3
#DANGER_DIST_DECAY  = 5

DANGER_DIST_RADIUS = 3
DANGER_DIST_DECAY  = 5




RATE_MOVE_STEP      = [0, 1, 2.1]
#RATE_MOVE_PERK      = -2
RATE_MOVE_TAKE_PERK = {
    EL.EPRIZE                  : -20, #Unknown type yet
    EL.EPRIZE_IMMORTALITY      : -40,
    EL.EPRIZE_BREAKING_WALLS   : -25,
    EL.EPRIZE_WALKING_ON_WATER : -20,
    EL.EPRIZE_VISIBILITY       : -20,
    EL.EPRIZE_NO_SLIDING       : -15
}

#FIRE
RATE_FIRE_PLAYER            = (-8, -24)[FORCE_ATTACK_PLAYERS]
RATE_FIRE_PLAYER_SAME_POS   = -30
RATE_FIRE_PLAYER_FORCE_DUEL = -RATE_DEATH-50 #even if die fire


RATE_FIRE_ZOMBIE            = (-8, -12)[FORCE_HARVEST]
RATE_FIRE_ZOMBIE_DUEL_SAFE  = -15
RATE_FIRE_ZOMBIE_EST_STUCK  = -8
RATE_FIRE_ZOMBIE_FORCE_DUEL = -RATE_DEATH-50 #even if die fire

PENALTY_FIRE_PERK = 10

RATE_FIRE_TREE = -0.5

RATE_FIRE_MAKE_SHOT = -5

FIRE_CUSTOM_RATES = {
    EL.EWALL_1_3: RATE_FIRE_MAKE_SHOT-1,
    EL.EWALL_2_3: RATE_FIRE_MAKE_SHOT-2,
    EL.EWALL    : RATE_FIRE_MAKE_SHOT,
}

RATE_FIRE_SCALES = [1, 1, 0.9, 0.8, 0.8, 0.8, 0.8, 0.8, 0.7]




CUBE_HISTORY_LEN = 5
CUBE_LONG_HISTORY_LEN = 10

ATTACK_STARTS_RANGE_MIN = 2
ATTACK_STARTS_RANGE_MAX = 2

PLAYER_SAME_POSITION_DETECT = 20

